"""Abstract storage backend protocol for Kepler research data."""

from __future__ import annotations

from typing import Protocol

from domain.schemas.research import (
    PaperCandidate,
    ResearchConversation,
    ResearchJob,
    ResearchMessage,
    ResearchReport,
    ResearchTask,
)


class StorageBackend(Protocol):
    """Interface that any storage backend must implement."""

    # ── Tasks ──
    def save_task(self, task: ResearchTask) -> None: ...
    def load_task(self, task_id: str) -> ResearchTask | None: ...

    # ── Papers ──
    def save_papers(self, task_id: str, papers: list[PaperCandidate]) -> None: ...
    def load_papers(self, task_id: str) -> list[PaperCandidate]: ...

    # ── Reports ──
    def save_report(self, report: ResearchReport) -> None: ...
    def load_report(self, task_id: str, report_id: str | None = None) -> ResearchReport | None: ...

    # ── Conversations ──
    def save_conversation(self, conversation: ResearchConversation) -> None: ...
    def load_conversation(self, conversation_id: str) -> ResearchConversation | None: ...
    def list_conversations(self) -> list[ResearchConversation]: ...
    def delete_conversation(self, conversation_id: str) -> None: ...

    # ── Messages ──
    def save_messages(self, conversation_id: str, messages: list[ResearchMessage]) -> None: ...
    def load_messages(self, conversation_id: str) -> list[ResearchMessage]: ...

    # ── Jobs ──
    def save_job(self, job: ResearchJob) -> None: ...
    def load_job(self, job_id: str) -> ResearchJob | None: ...
    def list_jobs(self, *, conversation_id: str | None = None, task_id: str | None = None) -> list[ResearchJob]: ...
    def delete_jobs(self, *, conversation_id: str | None = None, task_id: str | None = None) -> None: ...

    # ── Cleanup ──
    def delete_task_artifacts(self, task_id: str) -> None: ...
    def clear_all(self) -> None: ...
